package main;

public class UsingException {

	public static void main(String[] args) {

		UsingException reference = new UsingException();
		System.out.println(reference.divide());
		
	}
	
	public int divide() {
		try {
			int num1 = 3;
			int num2 = 0;
			return num1/num2;
		} catch (ArithmeticException e) {
			System.out.println(e.getMessage());
			return 0;
		} finally {
			System.out.println("fish");
		}
	}

}
